-- require("interestingwords").setup {
-- 		colors = { '#ff00ff', '#ff0040', '#0000ff', '#00ff00', '#f05657', '#ffff00' },
-- 		search_count = true,
-- 		navigation = true,
-- 		scroll_center = true,
-- 		search_key = "<leader>f",
-- 		cancel_search_key = "<leader>c",
-- 		color_key = "<leader>k",
-- 		cancel_color_key = "<leader>l",
-- }
